### ISSUE TITLE
PROPOSAL: Georgia National Agency of Public Registry, GE-NAPR

### ISSUE THREAD

**Issue by markbrough** [org-id/register#72] opened 2017-10-09 11:50 UTC
The National Agency of Public Registry (NAPR) of Georgia registers all legal entities in Georgia. This includes government and non-government bodies (including the private sector). The ID assigned by NAPR is the same as the VAT number in Georgia. NAPR assigns codes for government bodies in addition to all non-governmental organisations (private and non-profit). The NAPR is a legal entity of public law under the Ministry of Justice.

## Proposal

National Agency of Public Registry, Georgia

Suggested code: GE-NAPR

Georgia (country)

All legal entities in Georgia, including: individual entrepreneur, commercial legal entity, nonprofit legal entity, legal entity of public law (government)

Covers all sectors

https://enreg.reestri.gov.ge/ (in Georgian, with a captcha for each request)

No open data copies of this list found.

Example: 416337084 - "Caucasus International Trade Ltd."

**Comment by BobHarper1** [comment] 2017-10-10 10:40
Hi @markbrough, thanks for your proposal, which looks like a viable register. We'll create a branch and a PR for this proposal at which point you can help to review prior to merging.

Another couple of title searches for testing:
- კათარზისი
- საქართველოს ბანკი

**Comment by BobHarper1** [comment] 2017-10-10 13:57
@markbrough I've open a new branch with the addition of this list. Can you check over it (if you have difficulties with the preview tool you can look at https://github.com/org-id/register/blob/3c91c14a07819f09bf2367efd337874787f519c9/lists/ge/ge-napr.json

P.S. thanks for the information that you provided, it was very complete.

**Comment by markbrough** [comment] 2017-10-10 15:34
Looks awesome - thanks! Though, the preview tool doesn't appear to work for me (in Firefox or Chrome).

**Comment by timgdavies** [comment] 2017-10-10 17:08
I've updated the list definition with ``"confirmed":true`` which allows it to display (sorry, a quirk of current update process... needs fixing) 

I'm just going to look at making a few other quick edits to set the register status and the links.

**Comment by BobHarper1** [comment] 2017-10-17 10:19
Merged #74

**Comment by duncandewhurst** [comment] 2018-09-20 10:50
Noting that the NAPR website looks to have been updated since it was added to the registry - there is now a captcha-free search which accepts registration number and other parameters in addition to the name of the organization.

**Comment by timgdavies** [comment] 2018-09-24 16:29
I've staged a small update to mention that it's possible to now search by number as well.

Let me know if other edits you think are needed.

**Closed by timgdavies** 2018-09-24 16:29 UTC
